name: Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: crystal docs -o /docs
      - name: Deploy
        run: |
          git config --global --add safe.directory $PWD
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}"
          git checkout -f --orphan gh-pages
          git rm --cached -rfq .
          git clean -fxdq
          mv /docs/* .
          git add .
          git commit -qm "Update docs"
          git push -f --set-upstream origin gh-pages
